CREATE DATABASE STUDENTMANAGEMENTBD;
USE STUDENTMANAGEMENTBD;


CREATE TABLE STUDENTS(
     STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
     STUDENT_NAME VARCHAR(100)  NOT NULL,
     STUDENT_GENDER ENUM('M','F','OTHER'),
     STUDENT_CONTACT VARCHAR(30),
     STUDENT_EMAIL VARCHAR(50)
);
CREATE TABLE SUBJECTS(
     SUBJECT_ID INT PRIMARY KEY AUTO_INCREMENT,
     SUBJECT_NAME VARCHAR(50)
     
);
CREATE TABLE MARKS(
     MARK_ID INT PRIMARY KEY AUTO_INCREMENT,
     STUDENT_ID INT,
     SUBJECT_ID INT,
     MARKS INT,
     FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (STUDENT_ID),
     FOREIGN KEY (SUBJECT_ID)REFERENCES SUBJECTS(SUBJECT_ID)
     
);
DELIMITER //
CREATE PROCEDURE ADDS_TUDENT(
IN STUDENT_NAME VARCHAR(50) ,
IN STUDENT_GENDER ENUM('M','F','OTHER'),
IN STUDENT_CONTACT VARCHAR(50),
IN STUDENT_EMAIL VARCHAR(50)

)
BEGIN
   INSERT INTO STUDENTS(STUDENT_NAME,STUDENT_GENDER,STUDENT_CONTACT,STUDENT_EMAIL)
   VALUES(STUDENT_NAME,STUDENT_GENDER,STUDENT_CONTACT,STUDENT_EMAIL);
END //
DELIMITER ;
CALL ADDS_TUDENT("SIJIT","F","+917430857114","SUJIT@GMAIL.COM");

SELECT * FROM STUDENTS;


INSERT INTO SUBJECTS( SUBJECT_NAME)
VALUES("COMPUTER SCIENCE"),("MATH"),("ENGLISG");

INSERT INTO MARKS (STUDENT_ID,SUBJECT_ID,MARKS)
VALUES(1,1,80),(1,2,70),(1,3,60);


INSERT INTO MARKS (STUDENT_ID,SUBJECT_ID,MARKS)
VALUES(2,1,85),(2,2,80),(2,3,70);

INSERT INTO MARKS (STUDENT_ID,SUBJECT_ID,MARKS)
VALUES(4,1,95),(4,2,54),(4,3,71);


SELECT M.MARK_ID,
       M.MARKS,
       S.SUBJECT_NAME, 
       ST.STUDENT_NAME 
       FROM MARKS AS  M
JOIN SUBJECTS S 
ON M.SUBJECT_ID=S.SUBJECT_ID
JOIN STUDENTS ST ON M.STUDENT_ID=ST.STUDENT_ID
ORDER BY MARK_ID;

SELECT S.STUDENT_ID,
S.STUDENT_NAME,
SUM(M.MARKS) AS SUM
FROM STUDENTS S JOIN MARKS M ON S.STUDENT_ID=M.STUDENT_ID
GROUP BY S.STUDENT_ID,S.STUDENT_NAME ORDER BY SUM DESC;

SELECT S.STUDENT_ID,
S.STUDENT_NAME,
SUM(M.MARKS) AS SUM
FROM STUDENTS S JOIN MARKS M ON S.STUDENT_ID=M.STUDENT_ID
GROUP BY S.STUDENT_ID,S.STUDENT_NAME ORDER BY SUM DESC LIMIT 1;


SELECT S.STUDENT_ID,
S.STUDENT_NAME,
AVG(M.MARKS) AS AVG
FROM STUDENTS S JOIN MARKS M ON S.STUDENT_ID=M.STUDENT_ID
GROUP BY S.STUDENT_ID,S.STUDENT_NAME ORDER BY AVG DESC ;

SELECT COUNT(*) AS TOTAL_STUDENT FROM STUDENTS;
